
package co.badge.kpsPublic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "KPSPublicV2", targetNamespace = "http://tckimlik.nvi.gov.tr/WS", wsdlLocation = "file:/home/furkaanasik/Projects/Java/Spring%20Boot/badge/src/main/resources/wsdl/KPSPublicV2.wsdl")
public class KPSPublicV2
    extends Service
{

    private final static URL KPSPUBLICV2_WSDL_LOCATION;
    private final static WebServiceException KPSPUBLICV2_EXCEPTION;
    private final static QName KPSPUBLICV2_QNAME = new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicV2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/furkaanasik/Projects/Java/Spring%20Boot/badge/src/main/resources/wsdl/KPSPublicV2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KPSPUBLICV2_WSDL_LOCATION = url;
        KPSPUBLICV2_EXCEPTION = e;
    }

    public KPSPublicV2() {
        super(__getWsdlLocation(), KPSPUBLICV2_QNAME);
    }

    public KPSPublicV2(WebServiceFeature... features) {
        super(__getWsdlLocation(), KPSPUBLICV2_QNAME, features);
    }

    public KPSPublicV2(URL wsdlLocation) {
        super(wsdlLocation, KPSPUBLICV2_QNAME);
    }

    public KPSPublicV2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KPSPUBLICV2_QNAME, features);
    }

    public KPSPublicV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KPSPublicV2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KPSPublicV2Soap
     */
    @WebEndpoint(name = "KPSPublicV2Soap")
    public KPSPublicV2Soap getKPSPublicV2Soap() {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicV2Soap"), KPSPublicV2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KPSPublicV2Soap
     */
    @WebEndpoint(name = "KPSPublicV2Soap")
    public KPSPublicV2Soap getKPSPublicV2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicV2Soap"), KPSPublicV2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns KPSPublicV2Soap
     */
    @WebEndpoint(name = "KPSPublicV2Soap12")
    public KPSPublicV2Soap getKPSPublicV2Soap12() {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicV2Soap12"), KPSPublicV2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KPSPublicV2Soap
     */
    @WebEndpoint(name = "KPSPublicV2Soap12")
    public KPSPublicV2Soap getKPSPublicV2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tckimlik.nvi.gov.tr/WS", "KPSPublicV2Soap12"), KPSPublicV2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KPSPUBLICV2_EXCEPTION!= null) {
            throw KPSPUBLICV2_EXCEPTION;
        }
        return KPSPUBLICV2_WSDL_LOCATION;
    }

}
